App\Entity\User:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity:
        fields: [email]
        message: Email address already in use
  properties:
    email:
        - NotBlank:
            message: Enter an email address
        - Email:
            message: The email {{ value }} is not a valid email.
    firstName:
        - NotBlank:
            message: Enter a first name
    lastName:
        - NotBlank:
            message: Enter a last name


App\Entity\Order:
  properties:
    hasAssetsAboveThreshold:
    - Type: string
    - NotBlank:
        message: "Please choose 'Yes' or 'No'"
        groups: [order-has-assets]
    subType:
    - Type: string
    - NotBlank:
        message: "Please choose the order subtype"
        groups: [order-subtype]
    appointmentType:
    - Type: string
    - NotBlank:
        message: "Please choose the appointment type"
        groups: [appointment-type]


App\Entity\Deputy:
    properties:
        deputyType:
            - Type: string
            - NotBlank:
                message: "Please select a deputy type"
                groups: [order-deputy]
        forename:
            - Type: string
            - NotBlank:
                message: "Please enter the deputy's first name"
                groups: [order-deputy]
        surname:
            - Type: string
            - NotBlank:
                message: "Please enter the deputy's surname"
                groups: [order-deputy]
        dateOfBirth:
            - Type: Date
            - Date:
                groups: [order-deputy]
        emailAddress:
            - Type: string
            - Email:
                message: The email {{ value }} is not a valid email.
                groups: [order-deputy]
            - Length:
                max: 60
                maxMessage: "The deputy's email address is too long"
                min: 7
                minMessage: "The deputy's email address is too short"
                groups: [order-deputy]
        daytimeContactNumber:
            - Type: string
            - Length:
                max: 20
                maxMessage: "The deputy's daytime contact number is too long"
                min: 10
                minMessage: "The deputy's daytime contact number is too short"
                groups: [order-deputy]
        eveningContactNumber:
            - Type: string
            - Length:
                max: 20
                maxMessage: "The deputy's evening contact number is too long"
                min: 10
                minMessage: "The deputy's evening contact number is too short"
                groups: [order-deputy]
        mobileContactNumber:
            - Type: string
            - Length:
                max: 20
                maxMessage: "The deputy's mobile number is too long"
                min: 10
                minMessage: "The deputy's mobile number is too short"
                groups: [order-deputy]
        addressLine1:
            - Type: string
        addressLine2:
            - Type: string
        addressLine3:
            - Type: string
        addressTown:
            - Type: string
        addressCounty:
            - Type: string
        addressPostcode:
            - Type: string
            - Length:
                min: 2
                minMessage: "The deputy's postcode is too short"
                max: 10
                maxMessage: "The deputy's postcode is too long"
                groups: [order-deputy]
