name: "[Security] Secret Scan on Push"

on: workflow_call

permissions:
  id-token: write
  contents: read

jobs:
  secret_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Trivy Secret Scan
        id: trivy_secret_scan
        uses: aquasecurity/trivy-action@b6643a29fecd7f34b3597bc6acb0a98b03d33ff8 # 0.33.1
        with:
          scan-type: fs
          scanners: secret
          exit-code: 1
          format: table
          timeout: 5m

      - name: Notify Slack on failure
        if: failure()
        uses: ./.github/workflows/_notify-slack.yml
        with:
          type: "secret_alert"
          branch: ${{ github.ref_name }}
          user: ${{ github.actor }}
          gh_url: "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          commit_message: "Trivy Secret Scan failed on push"
